---
  - name: Install a secure Apache webserver using Ansible
    hosts: all
    gather_facts: yes

    tasks:
      - name: Check httpd installation for RHEL7.x/CentOS 7.x
        yum:
          name: httpd
          state: latest
        when: ansible_distribution == "RedHat" and ansible_distribution_major_version == "7"
      
      - name: Check httpd installation for RHEL8.x/CentOS 8.x
        dnf:
          name: httpd
          state: latest
        when: ansible_distribution == "RedHat" and ansible_distribution_major_version == "8"

      - name: Copy modified conf file
        copy:
          src: files/httpd.conf
          dest: /etc/httpd/conf/httd.conf
          owner: root
          group: root
          mode: 0644

      - name: Copy modified SSL conf file
        copy:
          src: files/ssl.conf
          dest: /etc/httpd/conf.d/ssl.conf
          owner: root
          group: root
          mode: 0644
      
      - name: Enable httpd
        service:
          name: httpd
          enabled: yes

      - name: Create root directory for files
        file:
          path: /var/www/{{ ansible_hostname }}
          state: directory
          owner: root
          group: root
          mode: 0755

      - name: Copy self signed cert
        copy:
          src: files/apache.crt
          dest: /etc/pki/tls/certs/apache-selfsigned.crt
          owner: root
          group: root
          mode: 0600

      - name: Copy self signed key
        copy:
          src: files/rootCA.key
          dest: /etc/pki/tls/private/apache-selfsigned.key
          owner: root
          group: root
          mode: 0600

      - name: Lock down apache files to root
        ansible.builtin.file:
          path: /var/www/{{ ansible_hostname }}
          owner: root
          group: root
          mode: 0755
      
      - name: State httpd
        service:
          name: httpd
          state: started